### ISSUE TITLE
Panel Problem?

### ISSUE THREAD

**Issue by Joeysay** [S1SYPHOS/Gulp-Kirby-Starter-Kit#15] opened 2021-01-07 15:13 UTC
Hello there,

i am not really a developer so I am not sure if it is an issure of just problem by me. But the kit can only work if i add port:4000 under server:{connet:{}} in config.js. And if I open http://localhost:4000/panel/ direct, it shows error like this: (but http://127.0.0.1:4000/panel works. )

`Access to fetch at 'http://127.0.0.1:4000/api/system?view=panel' from origin 'http://localhost:4000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Any idea why is that?

**Comment by S1SYPHOS** [comment] 2021-01-07 16:20
Good catch! I'll investigate (and fix) this. 

The live server (under port 4000) aids in developing the frontend and isn't meant for accessing the panel. You may do that directly though, as you correctly pointed out.

**Comment by S1SYPHOS** [comment] 2021-07-21 17:44
I'll close this because I cannot reproduce your problem. Feel free to open this issue up again if need be.

**Closed as completed by S1SYPHOS** 2021-07-21 17:44 UTC
